export const communityPlaceAbi = [
  {
    type: 'function',
    name: 'createPlace',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'locationLabel', type: 'string' },
    ],
    outputs: [{ name: 'placeId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'joinPlace',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'placeId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'createProposal',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'placeId', type: 'uint256' },
      { name: 'title', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'goalWei', type: 'uint256' },
    ],
    outputs: [{ name: 'proposalId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'contribute',
    stateMutability: 'payable',
    inputs: [{ name: 'proposalId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitProof',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
      { name: 'proofUri', type: 'string' },
      { name: 'report', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'verify',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'proposalId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'placeCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'proposalCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getPlace',
    stateMutability: 'view',
    inputs: [{ name: 'placeId', type: 'uint256' }],
    outputs: [
      { name: 'name', type: 'string' },
      { name: 'locationLabel', type: 'string' },
      { name: 'creator', type: 'address' },
      { name: 'memberCount', type: 'uint256' },
      { name: 'treasury', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'getProposal',
    stateMutability: 'view',
    inputs: [{ name: 'proposalId', type: 'uint256' }],
    outputs: [
      { name: 'placeId', type: 'uint256' },
      { name: 'creator', type: 'address' },
      { name: 'title', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'goal', type: 'uint256' },
      { name: 'raised', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'proofUri', type: 'string' },
      { name: 'report', type: 'string' },
      { name: 'yesVotes', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'getReputation',
    stateMutability: 'view',
    inputs: [
      { name: 'placeId', type: 'uint256' },
      { name: 'member', type: 'address' },
    ],
    outputs: [
      { name: 'contribution', type: 'uint256' },
      { name: 'execution', type: 'uint256' },
      { name: 'joined', type: 'bool' },
    ],
  },
] as const
